version: 0.2

exported-variables:
    - COSMOS_VERSION

phases:
  pre_build:
    commands:
      - certee-fetch

  build:
    commands:
       - cosmos-release --help service
       - mix deps.get
       - mix distillery.release
       - mkdir -p /root/rpmbuild/SOURCES
       - cp _build/prod/rel/origin_simulator/releases/*/origin_simulator.tar.gz /root/rpmbuild/SOURCES/
       - cp origin-simulator.spec /root/rpmbuild/SOURCES/
       - cp SOURCES/origin_simulator.service /root/rpmbuild/SOURCES/
       - cp SOURCES/performance.conf /root/rpmbuild/SOURCES/
       - cd /root/rpmbuild/SOURCES
       - echo "Generating version file"
       - export COSMOS_VERSION=`cosmos-release generate-version origin-simulator`
       - rpmbuild -ba --define "cosmos_version ${COSMOS_VERSION}" origin-simulator.spec
       - echo "Releasing 'RPMS/x86_64/*.x86_64.rpm' to origin-simulator"
       - cosmos-release service origin-simulator --release-version=v /root/rpmbuild/RPMS/x86_64/*.x86_64.rpm

