version: 0.2

exported-variables:
    - COSMOS_VERSION

phases:
  pre_build:
    commands:
      - certee-fetch

  build:
    commands:
       - mix deps.get
       - mix distillery.release
       - mkdir -p /root/rpmbuild/SOURCES
       - cp _build/prod/rel/origin_simulator/releases/*/origin_simulator.tar.gz /root/rpmbuild/SOURCES/
       - cp origin-simulator.spec /root/rpmbuild/SOURCES/
       - cp SOURCES/origin_simulator.service /root/rpmbuild/SOURCES/
       - cp SOURCES/performance.conf /root/rpmbuild/SOURCES/
       - cd /root/rpmbuild/SOURCES
       - echo "Generating version file"
       - export COSMOS_VERSION=`cosmos-release generate-version origin-simulator`
       - rpmbuild -ba --define "cosmos_version ${COSMOS_VERSION}" origin-simulator.spec
       - ls /root/rpmbuild/RPMS/
       - cosmos-release service origin-simulator /root/rpmbuild/RPMS/**/*.rpm --os=el8 --release-version=$COSMOS_VERSION

