version: 0.2

exported-variables:
    - COSMOS_VERSION

phases:
  pre_build:
    commands:
      - dnf install -y spectacle jq --disablerepo=epel # spectacle has a name clash with s/t in the el8 epel repo
  build:
    commands:
       - mix deps.get
       - mix distillery.release
       - cp _build/prod/rel/origin_simulator/releases/*/origin_simulator.tar.gz SOURCES/
       - cp origin-simulator.spec SOURCES/
       - cd SOURCES
       - echo "Generating version file"
       - export COSMOS_COMPONENT_NAME='origin-simulator'
       - export COSMOS_VERSION=`cosmos-release generate-version ${COSMOS_COMPONENT_NAME}`
       - echo COSMOS_VERSION=$COSMOS_VERSION
       - spectacle $COSMOS_VERSION
       - rpmbuild -ba origin-simulator.spec