version: 0.2

exported-variables:
    - COSMOS_VERSION

phases:
  build:
    commands:
       - mix deps.get
       - mix distillery.release
       - mkdir -p ./root/rpmbuild/SOURCES
       - pwd
       - cp _build/prod/rel/origin_simulator/releases/*/origin_simulator.tar.gz ./root/rpmbuild/SOURCES/
       - cp origin-simulator.spec ./root/rpmbuild/SOURCES/
       - cp SOURCES/origin_simulator.service ./root/rpmbuild/SOURCES/
       - cp SOURCES/performance.conf ./root/rpmbuild/SOURCES/
       - cd ./root/rpmbuild/SOURCES
       - pwd
       - ls -l
       - echo "Generating version file"
       - export COSMOS_VERSION=`cosmos-release generate-version origin-simulator`
       - echo COSMOS_VERSION=87
       - rpmbuild -ba origin-simulator.spec
